# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-20 14:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('browser', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CPCHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500, verbose_name='投放链接')),
                ('click_nums', models.PositiveIntegerField(default=0, verbose_name='投定量')),
                ('ip_nums', models.PositiveIntegerField(default=0, verbose_name='已投放IP')),
                ('pv_nums', models.PositiveIntegerField(default=0, verbose_name='已投放PV')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'CPC历史数据',
                'verbose_name': 'CPC历史数据',
            },
        ),
        migrations.CreateModel(
            name='CPCWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500, verbose_name='投放链接')),
                ('click_nums', models.PositiveIntegerField(default=0, verbose_name='投定量')),
                ('hasclicked', models.PositiveIntegerField(default=0, verbose_name='已投放点击量')),
                ('ip_nums', models.PositiveIntegerField(default=0, verbose_name='已投放IP')),
                ('is_control', models.PositiveSmallIntegerField(choices=[(0, '否'), (1, '是')], verbose_name='是否控量')),
                ('status', models.PositiveSmallIntegerField(default=0, verbose_name='状态')),
                ('remark', models.CharField(max_length=255, verbose_name='备注')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='投放时间')),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.ClickTask', verbose_name='任务ID')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='任务发布人')),
            ],
            options={
                'verbose_name_plural': 'CPC业务',
                'verbose_name': 'CPC业务',
            },
        ),
        migrations.CreateModel(
            name='CPMHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500, verbose_name='投放链接')),
                ('click_nums', models.PositiveIntegerField(default=0, verbose_name='投定量')),
                ('ip_nums', models.PositiveIntegerField(default=0, verbose_name='已投放IP')),
                ('pv_nums', models.PositiveIntegerField(default=0, verbose_name='已投放PV')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'CPM历史数据',
                'verbose_name': 'CPM历史数据',
            },
        ),
        migrations.CreateModel(
            name='CPMWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500, verbose_name='投放链接')),
                ('click_nums', models.PositiveIntegerField(default=0, verbose_name='投定量')),
                ('ip_nums', models.PositiveIntegerField(default=0, verbose_name='已投放IP')),
                ('pv_nums', models.PositiveIntegerField(default=0, verbose_name='已投放PV')),
                ('is_control', models.PositiveSmallIntegerField(choices=[(0, '否'), (1, '是')], verbose_name='是否控量')),
                ('status', models.PositiveSmallIntegerField(default=0, verbose_name='状态')),
                ('remark', models.CharField(max_length=255, verbose_name='备注')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='投放时间')),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.ClickTask', verbose_name='任务ID')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='任务发布人')),
            ],
            options={
                'verbose_name_plural': 'CPM业务',
                'verbose_name': 'CPM业务',
            },
        ),
        migrations.CreateModel(
            name='RankWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500, verbose_name='投放链接')),
                ('click_nums', models.PositiveIntegerField(default=0, verbose_name='投定量')),
                ('hasclicked', models.PositiveIntegerField(default=0, verbose_name='已投放点击量')),
                ('ip_nums', models.PositiveIntegerField(default=0, verbose_name='已投放IP')),
                ('is_control', models.PositiveSmallIntegerField(choices=[(0, '否'), (1, '是')], verbose_name='是否控量')),
                ('status', models.PositiveSmallIntegerField(default=0, verbose_name='状态')),
                ('remark', models.CharField(max_length=255, verbose_name='备注')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='投放时间')),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.ClickTask', verbose_name='任务ID')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='任务发布人')),
            ],
            options={
                'verbose_name_plural': '排名业务',
                'verbose_name': '排名业务',
            },
        ),
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('urls', models.TextField(verbose_name='URL明细')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='投放时间')),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='任务发布人')),
            ],
            options={
                'verbose_name_plural': '多URL列表',
                'verbose_name': '多URL列表',
            },
        ),
        migrations.AddField(
            model_name='cpmhistory',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.CPMWork', verbose_name='历史'),
        ),
        migrations.AddField(
            model_name='cpmhistory',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.ClickTask', verbose_name='任务ID'),
        ),
        migrations.AddField(
            model_name='cpmhistory',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='任务发布人'),
        ),
        migrations.AddField(
            model_name='cpchistory',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.CPCWork', verbose_name='历史'),
        ),
        migrations.AddField(
            model_name='cpchistory',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.ClickTask', verbose_name='任务ID'),
        ),
        migrations.AddField(
            model_name='cpchistory',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='任务发布人'),
        ),
    ]
