# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-23 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpcwork',
            name='is_control',
            field=models.PositiveSmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否控量'),
        ),
        migrations.AlterField(
            model_name='cpcwork',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='cpmwork',
            name='is_control',
            field=models.PositiveSmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否控量'),
        ),
        migrations.AlterField(
            model_name='cpmwork',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='rankwork',
            name='is_control',
            field=models.PositiveSmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否控量'),
        ),
        migrations.AlterField(
            model_name='rankwork',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='备注'),
        ),
    ]
