# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-25 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20170723_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpmwork',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '未开始'), (1, '正在执行'), (2, '完成'), (3, '任务暂停')], default=0, verbose_name='状态'),
        ),
    ]
