# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-25 09:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20170725_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpchistory',
            name='user_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='任务发布人'),
        ),
        migrations.AlterField(
            model_name='cpcwork',
            name='user_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='任务发布人'),
        ),
        migrations.AlterField(
            model_name='cpmhistory',
            name='user_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='任务发布人'),
        ),
        migrations.AlterField(
            model_name='cpmwork',
            name='user_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='任务发布人'),
        ),
        migrations.AlterField(
            model_name='rankwork',
            name='user_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='任务发布人'),
        ),
        migrations.AlterField(
            model_name='urls',
            name='user_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='任务发布人'),
        ),
    ]
