# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-26 09:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20170725_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpcwork',
            name='task_time',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='cpmwork',
            name='task_time',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
