# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-26 10:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20170726_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankwork',
            name='task_time',
            field=models.DateField(default=datetime.date.today, verbose_name='投放时间'),
        ),
        migrations.AlterField(
            model_name='cpcwork',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cpcwork',
            name='task_time',
            field=models.DateField(default=datetime.date.today, verbose_name='投放时间'),
        ),
        migrations.AlterField(
            model_name='cpmwork',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cpmwork',
            name='task_time',
            field=models.DateField(default=datetime.date.today, verbose_name='投放时间'),
        ),
        migrations.AlterField(
            model_name='rankwork',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
