# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-20 14:10
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('url_md5', models.CharField(db_column='url_MD5', max_length=32, unique=True)),
                ('task_type', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('task_detail', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('task_status', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('task_bili', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('task_time', models.DateField(default=datetime.date.today)),
                ('task_area', models.CharField(default=0, max_length=255, validators=['validate_comma_separated_integer_list'])),
                ('request', models.PositiveSmallIntegerField(default=0)),
                ('referer', models.CharField(max_length=500)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('bk1', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='任务发布人')),
            ],
        ),
        migrations.CreateModel(
            name='TaskCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_md5', models.CharField(db_column='url_MD5', max_length=32, unique=True)),
                ('finish_count', models.PositiveIntegerField(default=0)),
                ('task_count', models.PositiveIntegerField(default=0)),
                ('task_status', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('bk1', models.CharField(blank=True, max_length=255, null=True)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.ClickTask', verbose_name='任务ID')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_md5', models.CharField(db_column='url_MD5', max_length=32, unique=True)),
                ('field_0', models.PositiveIntegerField(blank=True, db_column='_0', null=True)),
                ('field_1', models.PositiveIntegerField(blank=True, db_column='_1', null=True)),
                ('field_2', models.PositiveIntegerField(blank=True, db_column='_2', null=True)),
                ('field_3', models.PositiveIntegerField(blank=True, db_column='_3', null=True)),
                ('field_4', models.PositiveIntegerField(blank=True, db_column='_4', null=True)),
                ('field_5', models.PositiveIntegerField(blank=True, db_column='_5', null=True)),
                ('field_6', models.PositiveIntegerField(blank=True, db_column='_6', null=True)),
                ('field_7', models.PositiveIntegerField(blank=True, db_column='_7', null=True)),
                ('field_8', models.PositiveIntegerField(blank=True, db_column='_8', null=True)),
                ('field_9', models.PositiveIntegerField(blank=True, db_column='_9', null=True)),
                ('field_10', models.PositiveIntegerField(blank=True, db_column='_10', null=True)),
                ('field_11', models.PositiveIntegerField(blank=True, db_column='_11', null=True)),
                ('field_12', models.PositiveIntegerField(blank=True, db_column='_12', null=True)),
                ('field_13', models.PositiveIntegerField(blank=True, db_column='_13', null=True)),
                ('field_14', models.PositiveIntegerField(blank=True, db_column='_14', null=True)),
                ('field_15', models.PositiveIntegerField(blank=True, db_column='_15', null=True)),
                ('field_16', models.PositiveIntegerField(blank=True, db_column='_16', null=True)),
                ('field_17', models.PositiveIntegerField(blank=True, db_column='_17', null=True)),
                ('field_18', models.PositiveIntegerField(blank=True, db_column='_18', null=True)),
                ('field_19', models.PositiveIntegerField(blank=True, db_column='_19', null=True)),
                ('field_20', models.PositiveIntegerField(blank=True, db_column='_20', null=True)),
                ('field_21', models.PositiveIntegerField(blank=True, db_column='_21', null=True)),
                ('field_22', models.PositiveIntegerField(blank=True, db_column='_22', null=True)),
                ('field_23', models.PositiveIntegerField(blank=True, db_column='_23', null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('bk1', models.CharField(blank=True, max_length=255, null=True)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.ClickTask', verbose_name='任务ID')),
            ],
        ),
    ]
