# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-24 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0002_auto_20170724_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcount',
            name='task_status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
