# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-24 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0003_auto_20170724_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetask',
            name='field_0',
            field=models.PositiveIntegerField(db_column='_0', default=0),
        ),
        migrations.AlterField(
            model_name='timetask',
            name='field_1',
            field=models.PositiveIntegerField(db_column='_1', default=0),
        ),
        migrations.AlterField(
            model_name='timetask',
            name='field_10',
            field=models.PositiveIntegerField(db_column='_10', default=0),
        ),
        migrations.AlterField(
            model_name='timetask',
            name='field_11',
            field=models.PositiveIntegerField(db_column='_11', default=0),
        ),
        migrations.AlterField(
            model_name='timetask',
            name='field_12',
            field=models.PositiveIntegerField(db_column='_12', default=0),
        ),
        migrations.AlterField(
            model_name='timetask',
            name='field_13',
            field=models.PositiveIntegerField(db_column='_13', default=0),
        ),
        migrations.AlterField(
            model_name='timetask',
            name='field_14',
            field=models.PositiveIntegerField(db_column='_14', default=0),
        ),
        migrations.AlterField(
            model_name='timetask',
            name='field_15',
            field=models.PositiveIntegerField(db_column='_15', default=0),
        ),
        migrations.AlterField(
            model_name='timetask',
            name='field_16',
            field=models.PositiveIntegerField(db_column='_16', default=0),
        ),
        migrations.AlterField(
            model_name='timetask',
            name='field_17',
            field=models.PositiveIntegerField(db_column='_17', default=0),
        ),
        migrations.AlterField(
            model_name='timetask',
            name='field_18',
            field=models.PositiveIntegerField(db_column='_18', default=0),
        ),
        migrations.AlterField(
            model_name='timetask',
            name='field_19',
            field=models.PositiveIntegerField(db_column='_19', default=0),
        ),
        migrations.AlterField(
            model_name='timetask',
            name='field_2',
            field=models.PositiveIntegerField(db_column='_2', default=0),
        ),
        migrations.AlterField(
            model_name='timetask',
            name='field_20',
            field=models.PositiveIntegerField(db_column='_20', default=0),
        ),
        migrations.AlterField(
            model_name='timetask',
            name='field_21',
            field=models.PositiveIntegerField(db_column='_21', default=0),
        ),
        migrations.AlterField(
            model_name='timetask',
            name='field_22',
            field=models.PositiveIntegerField(db_column='_22', default=0),
        ),
        migrations.AlterField(
            model_name='timetask',
            name='field_23',
            field=models.PositiveIntegerField(db_column='_23', default=0),
        ),
        migrations.AlterField(
            model_name='timetask',
            name='field_3',
            field=models.PositiveIntegerField(db_column='_3', default=0),
        ),
        migrations.AlterField(
            model_name='timetask',
            name='field_4',
            field=models.PositiveIntegerField(db_column='_4', default=0),
        ),
        migrations.AlterField(
            model_name='timetask',
            name='field_5',
            field=models.PositiveIntegerField(db_column='_5', default=0),
        ),
        migrations.AlterField(
            model_name='timetask',
            name='field_6',
            field=models.PositiveIntegerField(db_column='_6', default=0),
        ),
        migrations.AlterField(
            model_name='timetask',
            name='field_7',
            field=models.PositiveIntegerField(db_column='_7', default=0),
        ),
        migrations.AlterField(
            model_name='timetask',
            name='field_8',
            field=models.PositiveIntegerField(db_column='_8', default=0),
        ),
        migrations.AlterField(
            model_name='timetask',
            name='field_9',
            field=models.PositiveIntegerField(db_column='_9', default=0),
        ),
    ]
