# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-25 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0006_auto_20170725_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='clicktask',
            name='remaintime',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clicktask',
            name='task_bili',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clicktask',
            name='task_detail',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clicktask',
            name='task_status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clicktask',
            name='task_type',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
