# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0008_auto_20170727_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clicktask',
            name='request',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
