# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-20 14:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('browser', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.CharField(max_length=10, verbose_name='充值款')),
                ('remark', models.CharField(max_length=255, verbose_name='标记说明')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='充值日期')),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '充值记录',
                'verbose_name': '充值记录',
            },
        ),
        migrations.CreateModel(
            name='MyConsume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, '扣款'), (1, '退款')], verbose_name='类型')),
                ('reason', models.CharField(max_length=255, verbose_name='消费内容')),
                ('money', models.CharField(max_length=10, verbose_name='金额')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.ClickTask', verbose_name='业务ID')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '消费记录',
                'verbose_name': '消费记录',
            },
        ),
    ]
